### ISSUE TITLE
usdz texture support

### ISSUE THREAD

**Issue by peterurbanec** [ospray/hdospray#16]
I've built hdospray against USD23.05 and am testing with `usdview` on Linux.

Loading usda assets with texture files in a subdirectory works as expected. Loading **usdz** assets fails to load textures with error messages such as: `#osp: failed to load texture '/home/peteru/Downloads/USD/teapot.usdz[0/teapot_bc.png]'`

This is coming from `LoadOIIOTexture2D()`, which uses OIIO to load textures and it seems that OIIO does not support loading textures embedded in usdz files. I would expect that `LoadUDIMTexture2D()` would probably behave similarly as it uses the same strategy to load the texture file.

**Comment by carsonbrownlee** [comment]
hi Peter,
The next hdospray release, 1.0, uses HdIO instead of OIIO, which works with usdz files directly and is built with USD 23.02. If you need this immediately for personal use, let me know.  You can use usdz files with your current code by simply unzipping the usdz file, as all of the ones I have come across are just zipped usd directories.

**Comment by carsonbrownlee** [comment]
1.0 release resolves hio/usdz.
